---
- name: Apache server installed
  hosts: 152.7.176.227
  become: yes
  tasks:
  - name: Download NodeJS
    shell: 'curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
  - name: Install NodeJS
    apt: 
      name: nodejs
  # - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  #   community.crypto.openssh_keypair:
  #     path: /home/ynghatol/.ssh/id_githubkey
  - name: Basic usage
    debug:
      msg: "{{ GITHUBTOKEN }}"
  - name: Example clone of a single branch
    git:
      repo: https://{{ GITHUBTOKEN }}@github.ncsu.edu/csc510-s2022/CSC510-15.git
      dest: /home/ynghatol/CSC-510-15
      clone: yes
      update: yes
      accept_hostkey: yes

  - name: Install packages based on package.json using the npm.
    npm:
      path: /home/ynghatol/CSC-510-15/bot/
      state: present
  - name: Install Forever
    npm:
      name: forever
      global: yes
  - name: Fix 'support_tools' permissions
    shell: sudo chmod -R ugo+rwx /home/ynghatol/CSC-510-15/
